config/routes.rb
Staged::Engine.routes.draw do

  get  'changes/index'
  post 'changes/commit'
  post 'changes/reset'
  get "styles/index"

  post 'form/sendit'


  resources :pages , except: [:edit , :new] , shallow: true  do
    resources :sections do
      get :set_image
      get :select_template
      get :set_template
      get :select_card_template
      get :set_card_template
      get :move
      resources :cards do
        get :set_image
        get :move
      end
    end
  end
  resources :images do
    get :copy
    post :crop
    post :scale
  end

  resources  :translations
end

app/models/staged/active_base.rb
module Staged
  class ActiveBase < ActiveYaml
    fields :updated_at , :updated_by

    def edit_save( editor )
      self.updated_at = Time.now
      self.updated_by = editor
      edit_save!(editor)
    end

    def edit_save!(editor)
      ChangeSet.current.edit(self.class.name , self.change_name, editor)
      self.class.save_all
    end

    def add_save( editor )
      self.updated_at = Time.now
      self.updated_by = editor
      add_save!(editor)
    end

    def add_save!(editor)
      ChangeSet.current.add(self.class.name , self.change_name, editor)
      self.class.save_all
    end

    def delete_save!(editor)
      ChangeSet.current.delete(self.class.name , self.change_name,editor)
      self.class.delete(self.id)
      self.class.save_all
    end

  end
end

app/models/staged/active_yaml.rb
module Staged
  class ActiveYaml
    attr :data   #data of the instance, hash

    # retain the given hash data instance
    def initialize(data)
      @data = data
      # some checks, eg values are only fields
    end

    def id
      data[:id]
    end
    def id=(new_id)
      raise "Id must be number not (#{new_id})" unless new_id.is_a?(Integer)
      data[:id] = new_id
    end

    extend ActiveModel::Naming
    include ActiveModel::Conversion

    def persisted?
      true
    end

    class_attribute :path # usually rails root, where data is stored
    class_attribute :yaml_file   # the loaded data as array
    class_attribute :field_names  # methos name for accessing / allowed fields

    class << self
      #return all yaml data converted
      def all
        self.reload if self.yaml_file.blank?
        yaml_file.collect{|item| self.new(item) }
      end

      def primary_key
        "id"
      end

      # loads the data from path, name implicit in class_name
      def set_root_path(path)
        self.path = path
      end

      def reload
        self.yaml_file = load_file
      end

      def first
        self.new(yaml_file.first)
      end

      def find( id )
        id = id.to_i unless id.is_a?(Integer)
        find_by( :id , id )
      end

      def find_by( field , value )
        found = yaml_file.detect { |record| record[field] == value }
        return nil unless found
        self.new(found)
      end

      def find_all( field , value )
        found = yaml_file.find_all { |record| record[field] == value }
        found.collect {|f| self.new(f)}
      end

      def define_access(field)
        define_method(field) do
          data[field]
        end
        define_method(:"#{field}=") do |new_val|
          data[field] = new_val
        end
        assoc , id = field.to_s.split("_") # ie field image_id
        define_association(assoc) if id == "id"  #creates method image
      end

      # aka belongs_to
      # define a method by given name that used id value and
      # name of association to get a model instance of the id
      def define_association(assoc)
        clazz = "Staged::#{assoc.to_s.capitalize}".constantize
        define_method(assoc) do
          id = data[:"#{assoc}_id"]
          clazz.find( id )
        end
      end

      # class defines fields, we define access methods and finder for each
      def fields(*fields)
        self.field_names = fields
        raise "Fields must be Array not #{fields.class}" unless fields.is_a?(Array)
        fields.each do |field|
          define_access(field)
          the_meta_class.define_method(:"find_by_#{field}") do |arg|
            find_by(field , arg)
          end
        end
      end

      # load the yaml data from path and class_name
      def load_file
        YAML.load(File.read(full_path) , permitted_classes: [Time , Symbol],aliases: true)
      end

      # filename for the data (load and save)
      # made up of the set dir (set_root_path) plus tableized class name
      def full_path
        mod , filename = self.name.split("::").collect{|p| p.underscore}
        full_name = mod + "/" + filename.tableize + ".yml"
        File.join(self.path , full_name )
      end

      #create a new data point by adding the hash
      def append(data)
        largest = 0
        yaml_file.each { |item| largest = item[:id] if item[:id] > largest }
        data[:id] = largest + 1
        yaml_file << data
        largest + 1
      end

      def save_all
        File.write( full_path , yaml_file.to_yaml)
      end

      def delete(id)
        yaml_file.delete_if{|record| record[:id] == id.to_i}
        true
      end

      def the_meta_class
        class << self
          self
        end
      end

    end
  end
end

app/models/staged/card.rb
module Staged

  class Card < ViewBase

    set_root_path Rails.root.join(Staged.data_dir)

    fields  :id , :index , :section_id
    fields  :text , :header, :image_name

    def change_name
      pagename = section ? section.page_name : section_id.to_s
      "#{pagename}:#{header}"
    end

    def missing_translations
      sum = 0
      Staged.language_strings.each do |lang|
        sum += 1 if get_translation(lang).is_old?
      end
      sum
    end

    def move_up
      swap_index_with(previous_card)
    end

    def move_down
      swap_index_with(next_card)
    end

    def previous_card
      section.cards.find{|card| card.index == index - 1}
    end

    def next_card
      section.cards.find{|card| card.index == index + 1}
    end

    # card templates are stored in the section so the all cards
    # have the same
    def template
      section.card_template
    end

    def template_style
      CardStyle.find_by_template( self.template )
    end

    def allowed_fields
      super + [:section_id]
    end

    def delete_and_reset_index(editor)
      delete_save!(editor)
      Section.find(section_id).reset_index
      Card.save_all
    end

    def object_type
      "Card"
    end

    def index_name
      "#{section.index}.#{self.index}"
    end

    def delete(editor)
      delete_translations(editor)
      delete_save!(editor)
    end

    def self.new_card(card_template , section_id , index)
      data = { section_id: section_id , index: index}
      template = CardStyle.find_by_template( card_template )
      template.fields.each do |key|
        data[key.to_sym] = "NEW"
      end
      new_id = Card.append(data)
      card = Card.new(data)
      card.add_default_options(template.options_definitions)
      card
    end

    def self.reload
      res = super()
      self.fix_translations
    end

  end
end

app/models/staged/card_style.rb
module Staged
  class CardStyle < Style
    set_root_path Rails.root.join(Staged.data_dir)

    fields  :template , :text , :header, :fields

    def card_preview
      "staged/card_preview/" + template
    end

  end
end

app/models/staged/change_set.rb
module Staged
  class ChangeSet


    def self.current
      @@current ||= ChangeSet.new
    end
    attr_reader :adds , :edits , :deletes , :last , :last_editor

    def initialize
      zero
    end

    def zero
      @adds = Set.new
      @edits = Set.new
      @deletes = Set.new
      @last = nil
      @last_editor = nil
    end

    def touch(editor)
      @last = Time.now
      @last_editor = editor
    end

    def add( type , text , editor)
      touch(editor)
      @adds << [typed(type) , text ]
    end

    def edit( type , text, editor)
      touch(editor)
      @edits << [typed(type) , text ]
    end
    def delete( type , text, editor)
      touch(editor)
      @deletes << [typed(type) , text ]
    end

    def added( type )
      type = type.to_sym
      @adds.select { |a| a.first == type }
    end
    def edited( type )
      type = type.to_sym
      @edits.select { |a| a.first == type }
    end
    def deleted( type )
      type = type.to_sym
      @deletes.select { |a| a.first == type }
    end

    def typed(class_name)
      class_name.split("::").last.to_sym
    end
  end
end

app/models/staged/option_definition.rb
module Staged

  # Quite simple mapping from name to usually  a selection of values.
  # Options have type that can be set but usually is inferred from
  # wether there is one values (select) other wise text.
  # date is also supported.
  #
  # a corresponding ./app/views/staged/sections/_option_form_TYPE.haml
  # nust exist to render the type.
  #
  # Also values may be provided by a module function/attribute on Staged.
  # eg option text_color (also shade_color) have a Staged.text_color that return a
  # hash. In this case so it is easy to customize the colors of the app.
  #
  class OptionDefinition < SharedBase

    set_root_path Rails.root.join(Staged.data_dir)

    fields :name , :default , :description , :values , :type

    def type
      return data[:type] unless data[:type].blank?
      if has_values?
        "select"
      else
        "text"
      end
    end

    def has_values?
      return true if Staged.respond_to?( name.to_sym )
      return false if data[:values].nil?
      ! data[:values].empty?
    end

    def values
      return Staged.send(name.to_sym).keys if Staged.respond_to?( name.to_sym )
      return [] unless has_values?
      data[:values].split(" ")
    end

  end
end

app/models/staged/page_style.rb
module Staged
  class PageStyle < Style
    set_root_path Rails.root.join(Staged.data_dir)

    fields  :type , :description , :section_template

    def section_preview
      "staged/section_preview/" + section_template
    end

  end
end

app/controllers/staged/application_controller.rb
module Staged
  class ApplicationController < ActionController::Base
  end
end

app/controllers/staged/cards_controller.rb
module Staged
  class CardsController < StagedController
    before_action :set_card , except: [:index , :new]

    def index
      @section = Section.find(params[:section_id])
    end

    def set_image
      @card.image_id = params[:image_id].to_i
      @card.edit_save(current_member_email)
      message = @card.image ? "#{@card.image.name} selected" : "Image removed"
      redirect_to section_cards_url(@card.section.id) , notice: message
    end

    def move
      if( params[:dir] == "up")
        @card.move_up
      else
        @card.move_down
      end
      @card.edit_save(current_member_email)
      redirect_to section_cards_url(@card.section.id),notice: "#{@card.header} moved"
    end

    def new
      @section = Section.find(params[:section_id])
      new_card =  @section.new_card
      new_card.add_save(current_member_email)
      redirect_to section_cards_url(@section.id) , notice: "Card created"
    end

    def destroy
      @card.delete_and_reset_index(current_member_email)
      redirect_to section_cards_url(@card.section.id) , notice: "#{@card.header} removed"
    end

    def update
      @card.update(params[:card])
      @card.update_options( params[:options])
      @card.edit_save(current_member_email)
      respond_to do |format|
         format.html do
           redirect_to section_cards_url(@card.section_id) , notice: "Updated #{@card.header}"
         end
         format.json { render status: 200, json: {} }
       end

    end

    private
    def set_card
      card_id = params[:id] || params[:card_id]
      @card = Card.find( card_id )
    end

  end
end

app/controllers/staged/changes_controller.rb
require "open3"

module Staged
  class ChangesController < StagedController

    def index
    end

    def commit
      if params[:message].blank?
        message = "must have message"
        redirect_to changes_index_url , alert: message
      else
        out = capture("git add staged")
        out = capture("git add #{Image.asset_root}" , out)
        out = capture("git config --local user.email #{current_member_email}" ,out)
        out = capture('git commit -m "' + params[:message] + '"' ,out)
        out = capture("git pull --rebase=true" ,out)
        out = capture("git push" ,out)
        ChangeSet.current.zero
        redirect_to changes_index_url , notice: "Changes commited, #{out}"
      end
    end

    def reset
      begin
        out = capture("git checkout #{Staged.data_dir}")
        out = capture("git checkout #{Staged::Image.asset_root}" , out)
        ChangeSet.current.zero
        message = "Changes reset"
      rescue
        message = "Unknown error occured"
      end
      redirect_to changes_index_url , notice: message
    end

    private
    def capture(cmd , previous = "")
      out , ignore_status = Open3.capture2e(cmd)
      puts "CMD:#{ignore_status}: #{cmd}"
      puts out
      previous + "\n" + out
    end
  end
end

app/controllers/staged/form_controller.rb
module Staged
  class FormController < ::ApplicationController

    def post
      @section = Section.find( params[:section_id] )
      @errors = { }
      return if bot_alert
      check_maths
      verify_data
      if( @errors.length > 0)
        render "staged/form/form"
      else
        dispatch_form_data( )
        redirect_to main_app.root_url , notice: @section.option("ok_message")
      end
    end

    private

    def dispatch_form_data
      puts "Dispatch data"
      data = {}
      @section.cards.each do |card|
        data[card.header] = params[card.header]
      end
      if(@section.has_option?("handler") )
        puts "Sending data"
        @section.option("handler").constantize.new.handle_form(@section, data)
      end
    end

    def verify_data
      @section.cards.each do |card|
        check_option( card , params[card.header])
      end
    end
    def check_option(card , value)
      return unless value.blank?
      compulsory = card.option("compulsory") != "no"
      return unless compulsory
      # check different types
      message = card.text
      message = "May not be empty" if message.blank?
      @errors[card.header] = message
    end

    def check_maths
      key = params[:bot_fudder].to_i / 2
      if( (2*key + 1).to_s != params[:challenge])
        @errors[:challenge] = "Check the anti bot maths, it wasn't: #{params[:challenge]}"
      end
    end

    def bot_alert
      if @section.nil?
        head :ok
        return true
      end
      key = params[:bot_fudder]
      if key.to_i.to_s != key
        head :ok
        return true
      end
      return false
    end
  end
end

app/controllers/staged/images_controller.rb
require "mini_magick"

module Staged
  class ImagesController < StagedController
    before_action :set_image, only: %i[ update destroy show scale crop copy ]

    def index
      @images = get_images
      @image_data = @images.collect{|i|
        data = i.data.dup
        data[:url] = view_context.asset_path(i.asset_name)
        data[:link] = build_select_link_for(i)
        data[:updated_at] = i.updated_at.to_date if i.updated_at
        data[:created] = i.updated_at.to_i
        data[:aspect_ratio] = i.aspect_ratio.join("/")
        data[:ratio] = i.aspect_ratio
        data
      }
    end

    def destroy
      @image.destroy(current_member_email)
      redirect_to :images , notice: "Image #{@image.name} deleted"
    end

    def update
      @image.name = params[:name]
      @image.tags = params[:tags]
      @image.edit_save(current_member_email)
      redirect_to image_path(@image) , notice: "Image updated"
    end

    def scale
      @image.scale( params[:scale] )
      @image.edit_save(current_member_email)
      redirect_to image_path(@image) , notice: "Image was scaled"
    end

    def crop
      size = "#{params[:size_x]}x#{params[:size_y]}+#{params[:off_x]}+#{params[:off_y]}"
      @image.crop( size )
      @image.edit_save(current_member_email)
      redirect_to image_path(@image) , notice: "Image was resized"
    end

    def show
      @sections = Section.find_all(:image_id, params[:id].to_i)
      @cards = Card.find_all(:image_id, params[:id].to_i)
      @used = ((@cards.length > 0) || (@sections.length > 0))
      @image_data = @image.data
    end

    def copy
      image = @image.copy
      image.add_save(current_member_email)
      redirect_to image_path(image.id) , notice: "Image copied"
    end

    def create
      image = Image.create_new(params['filename'] ,params['tags'], params['image_file'])
      image.add_save current_member_email
      where_to  = determine_redirect(image)
      redirect_to where_to , notice: "New image created: #{image.name}"
    end

    private

    def get_images
      images = Image.all
      return images unless params[:unused]
      hash = images.collect{|i| [i.id , i ] }.to_h
      Section.all.each{ |s| hash.delete(s.image&.id)}
      Card.all.each{ |s| hash.delete(s.image&.id)}
      hash.values
    end
    def set_image
      @image = Image.find(params[:id] || params[:image_id])
    end
    def determine_redirect(image)
      if(params[:section_id])
        view_context.section_set_image_url(params[:section_id],image_id: image.id )
      elsif(params[:card_id])
        view_context.card_set_image_url(params[:card_id],image_id: image.id )
      else
         :images
      end
    end

    def build_select_link_for(image)
      if(params[:section_id])
        return view_context.section_set_image_url(params[:section_id] , image_id: image.id)
      end
      if(params[:card_id])
        return view_context.card_set_image_url(params[:card_id] , image_id: image.id)
      end
      view_context.image_url(image.id)
    end
  end

end

app/views/staged/sections/_option_form_date.haml
%label.block
  .mt-4.text-lg.font-bold
    = option.name.camelcase
.col-span-2= select_date section.option(option.name) , :prefix => "options[#{option.name}]"

app/views/staged/sections/_option_form_select.haml
%label.block
  .mt-4.text-lg.font-bold
    = option.name.camelcase
.col-span-2= select_tag( "options[#{option.name}]" , options_for_select(option.values, section.option(option.name)), class: "w-full rounded-lg border-gray-200 p-4 pr-12 text-sm shadow-sm")

app/views/staged/sections/_option_form_text.haml
%label.block
  .mt-4.text-lg.font-bold
    = option.name.camelcase
.col-span-2= text_field_tag( "options[#{option.name}]" , section.option(option.name), class: "w-full rounded-lg border-gray-200 p-4 pr-12 text-sm shadow-sm")

app/views/staged/sections/_overlay.haml
:javascript
  var authenticity_token = "#{form_authenticity_token}"

:opal
  Document.ready? do
    init_section
  end

:css
  #overlay {
    position: fixed;
    display: none;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0,0,0,0.5);
    z-index: 2;
    cursor: pointer;
  }

  #text {
    position: absolute;
  }
#overlay
  #text.text-gray-800
    %input.header.mt-1.w-full.rounded-md.border-gray-200.bg-white.shadow-sm{ id: "_header", type: "text" , value: "trans.header"}
    %textarea.textarea.mt-2.w-full.rounded-lg.border-gray-200.align-top.shadow-sm.sm:text-sm{ cols: 100 , rows: 10 }

    %button#hidden_button.button.change.mt-4{type: :submit }
      Update Texts

app/views/staged/sections/_sections_pagination.haml
.text-xl.font-bold.text-gray-900
  = section.page.type.capitalize
  \:
  = link_to section.page.name, staged.page_sections_path(section.page.id), class: "underline text-3xl ml-3"
.text-xl.font-bold.text-gray-900
  %span
    Section
    \:
    = link_to section.header, section_path(section), class: "underline text-3xl ml-3"

.inline-flex.items-center.justify-center.gap-3
  - if section.previous_section
    =link_to staged.section_path(section.previous_section.id) , class: "inline-flex h-8 w-8 items-center justify-center rounded border border-gray-100 hover:bg-sky-100" do
      %span.sr-only Next Section
      %svg.h-3.w-3{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", :d => "M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z", "fill-rule" => "evenodd"}
  - else
    .inline-flex.h-8.w-8.items-center.justify-center.rounded.border.border-gray-100
  %p.text-xs
    = section.index
    %span{:class => "mx-0.25"} /
    = section.page.sections.length
  - if section.next_section
    =link_to staged.section_path(section.next_section.id), class: "inline-flex h-8 w-8 items-center justify-center rounded border border-gray-100 hover:bg-sky-100" do
      %span.sr-only Next Section
      %svg.h-3.w-3{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", :d => "M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z", "fill-rule" => "evenodd"}
  - else
    .inline-flex.h-8.w-8.items-center.justify-center.rounded.border.border-gray-100

app/views/staged/sections/index.haml
.mx-6.md:mx-12.mx-20.flex.h-16.items-center.gap-16.mb-10
  .text-xl.font-bold.text-gray-900
    = @page.type.capitalize
    = link_to @page.name , staged.page_path(@page)
  .text-xl.text-gray-900
    =link_to "View live" , "/#{@page.name}" , target: @page.name
  = link_to( staged.new_page_section_path(@page.id) ) do
    %button.button.change New Section

-@page.sections.each do |section |
  .flex.gap-10.mt-2.pt-4.pb-2.border-2.bg-neutral-50.border-slate-400{ id: "section_#{section.id}"}
    .basis-72.ml-20
      %h3.text-lg.font-bold Section #{section.index} : #{section.header}
      .flex.flex-wrap.gap-3
        = link_to staged.section_path(section.id) do
          %button.button.action Edit
        = link_to staged.new_page_section_path(@page.id, template: section.template) do
          %button.button.change Copy
        .p-2
          =link_to(staged.section_move_path(section.id , dir: :down)) do
            %svg.w-6.h-6{:fill => "none", :stroke => "currentColor", "stroke-width" => "1.5", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
              %path{:d => "M15.75 17.25L12 21m0 0l-3.75-3.75M12 21V3", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
        .p-2
          =link_to(staged.section_move_path(section.id , dir: :up)) do
            %svg.w-6.h-6{:fill => "none", :stroke => "currentColor", "stroke-width" => "1.5", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
              %path{:d => "M8.25 6.75L12 3m0 0l3.75 3.75M12 3v18", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
        .basis-full.mt-3
          Updated at:
          = distance_of_time_in_words_to_now(section.updated_at)
        .basis-full.mb-3
          Updated by:
          = updated_by(section)
        - if section.has_cards?
          - if card = section.cards_update
            .basis-full
              Cards updated at:
              = distance_of_time_in_words_to_now(card.updated_at)
            .basis-full.mb-3
              Cards updated by:
              = card.updated_by
        .basis-full.mb-3
        = form_tag( staged.section_path(section.id) , {method: :delete  } ) do
          %button.button.remove{type: :submit} Delete

    .basis-72
      .flow.flow-cols
        %h3.text-lg.font-bold.border-bottom-2 Style
        = link_to(staged.section_select_template_path(section.id)) do
          %p= section.template_style.header
          = section_preview(section , class: "object-contain")
    .basis-52.grow
      %h3.my-4.text-lg.font-bold Header
      %p= section.header
      %h3.mt-4.text-lg.font-bold Text
      %p= section.text[0..100] + " ..." if section.text
    .basis-72
      - if section.has_cards?
        %h3.text-lg.font-bold #{section.cards.length} Cards
        =link_to staged.section_cards_path(section.id) do
          =card_preview(section , class: "object-contain")
      - else
        = link_to(staged.images_path(section_id: section.id)) do
          -if section.image
            %h3.text-lg.font-bold Image #{section.image.name}
            .flex.align-center.justify-between.mb-4
              .text-lg.font-bold.mt-2.mx-2
                = section.image.size.to_s + "k"
              %strong.inline-block.rounded.bg-gray-200.px-3.py-1.text-md.font-medium
                = section.image.aspect_ratio
            = image_for( section , "h-40 mb-1")
          -else
            %h3.mt-y.text-lg.font-bold No Image
    .basis-96
      %h3.text-lg.font-bold Options
      .grid.grid-cols-2.gap-3.mx-10
        - section.safe_options.each do|name , value|
          -unless value.blank?
            .font-bold.mt-1= name.camelcase
            .font-xl= value
.grid.grid-cols-2.gap-2.m-8
  .relative.block
    = link_to staged.new_page_section_path(@page.id) do
      %button.button.change New Section
  .relative.block.delete_page
    = form_tag( staged.page_path(@page.id) , {method: :delete  } ) do
      %button.button.remove{type: :submit} Delete Page

app/views/staged/sections/new.haml
.mx-6.md:mx-12.mx-20.flex.h-16.items-center.gap-16
  .text-xl.font-bold.text-gray-900
    Changes
  .text-xl.text-gray-900
    Branch
    = @git.current_branch

%h1 New staged_section

= render 'form'

= link_to 'Back', staged.sections_path

app/views/staged/sections/select_card_template.haml
.mx-6.md:mx-12.mx-20.flex.h-16.items-center.gap-16
  .text-xl.font-bold.text-gray-900
    Page #{link_to @section.page.name, staged.page_sections_path(@section.page.id), class: "underline"}
  .text-xl.text-gray-900
    Select Card Style for Section #{@section.index} - #{@section.header}

.grid.grid-cols-4.gap-6.m-8
  - @cards.each do |style|
    .flex.flex-col.border.border-gray-300.rounded-lg.p-2.bg-neutral-50
      = link_to( staged.section_set_card_template_path( card_template: style.template )) do
        .font-bold.text-lg.text-center.pb-4= style.header
        =image_tag(style.card_preview , class: "w-full object-contain")
        .text-left.pt-4.bg-gray-50= style.text

app/views/staged/sections/select_template.haml
.mx-6.md:mx-12.mx-20.flex.h-16.items-center.gap-16
  .text-xl.font-bold.text-gray-900
    Page #{link_to @section.page.name, staged.page_sections_path(@section.page.id), class: "underline"}
  .text-xl.text-gray-900
    Select Style for Section #{@section.index} - #{@section.header}

.grid.grid-cols-4.gap-6.my-10.mx-6.md:mx-12.mx-20
  - @sections.each do |style|
    .flex.flex-col.border.border-gray-300.rounded-lg.p-2.bg-neutral-50
      = link_to( staged.section_set_template_path( template: style.template )) do
        .font-bold.text-lg.text-center.pb-4= style.header
        =image_tag(style.section_preview , class: "w-full object-contain")
        .text-left.pt-4.bg-gray-50= style.text